name: moovy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shadcn_ui: ^0.28.5
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  injectable: ^2.5.1
  auto_route: ^10.1.0+1
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  currency_text_input_formatter: ^2.2.9
  sqflite: ^2.4.2
  json_annotation: ^4.9.0
  event_bus: ^2.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0
  auto_route_generator:
  build_runner: ^2.4.1
  injectable_generator:
  json_serializable: ^6.9.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "web/icons/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "windows/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "macos/image.png"
flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
